version: '3'

services:
  postgres:
    image: postgres:bullseye
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: postgres
      PGDATA: /pgdata 
    volumes: 
      - ./postgresdata:/pgdata:rw
  adminer:
    image: adminer
    ports:
      - "8080:8080"